version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes: # host/docker間で共有するデータを指定
      - "${HOME}/book-management_mysql:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: "Asia/Tokyo"
    ports:
      - "${DB_PORT}:${DB_PORT}"
  app:
    build:
      context: . # Dockerfileのディレクトリを指定
      args:
        UID: 1000
        GID: 1000
        UNAME: ubuntu
        INSTALL_XDEBUG: ${INSTALL_XDEBUG}
    user: ubuntu
    volumes: # host/docker間で共有するデータを指定
      - .:/srv
      - ./docker/nginx.conf:/etc/nginx/sites-enabled/bcm
      - ./docker/php-fpm.conf:/etc/php/7.2/fpm/pool.d/bcm.conf
      - ./docker/xdebug.ini:/etc/php/7.2/fpm/conf.d/xdebug.ini
    command: > # 起動処理を設定
      bash -c "chmod +x docker/entrypoint-app.sh && docker/entrypoint-app.sh"
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8000:8000"
    working_dir: /srv