version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup docker
          command: |
            docker-compose build
            docker-compose up -d
            docker-compose run app sudo composer install
      - run:
          name: Setup NodeJS and Yarn
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            source $BASH_ENV

            # Install NodeJS
            nvm install v12.16.1
            nvm alias default v12.16.1

            # Install Yarn
            npm install -g yarn@1.22.0
      - run: yarn install
      - run:
          name: Setup Laravel
          command: |
            cp .env.testing .env
            docker-compose run app php artisan key:generate
            docker-compose run app php artisan migrate:refresh --seed
      - run: yarn run build
      - run:
          name: Run Test
          command: |
            docker-compose run app vendor/bin/phpunit