version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup docker
          command: |
            docker-compose build
            docker-compose up -d
            docker-compose run app sudo composer install
      - run: yarn install
      - run:
          name: Setup Laravel
          command: |
            cp .env.testing .env
            docker-compose run app php artisan key:generate
            docker-compose run app php artisan migrate:refresh --seed
      - run: yarn run build
      - run:
          name: Run Test
          command: |
            docker-compose run app vendor/bin/phpunit